version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      # install Maven
      - echo Installing Maven...
      - yum install -y maven
build:
  commands:
    # MavenでSpring BootアプリケーションのJARファイルをビルド
    - echo Building JAR file...
    - mvn clean install -DskipTests
    # Dockerイメージをビルド
    - echo Building Docker image...
    - docker build -t 211125652233.dkr.ecr.eu-north-1.amazonaws.com/collaborative-notes .

post_build:
  commands:
    # ECRにログイン
    - echo Logging in to Amazon ECR...
    - $(aws ecr get-login --no-include-email --region your-region)
    # ECRリポジトリにタグ付け
    - echo Tagging Docker image...
    - docker tag your-ecr-repository-name:latest 211125652233.dkr.ecr.your-region.amazonaws.com/211125652233.dkr.ecr.eu-north-1.amazonaws.com/collaborative-notes:latest
    # DockerイメージをECRにプッシュ
    - echo Pushing Docker image to ECR...
    - docker push 211125652233.dkr.ecr.eu-north-1.amazonaws.com/collaborative-notes:latest

artifacts:
  files:
    - target/*.jar
  discard-paths: yes
