version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # Install OpenJDK 17
      - echo Installing OpenJDK 17...
      - sudo apt-get update -y
      - sudo apt-get install -y openjdk-17-jdk
      - java -version

      # Install MariaDB client (if not set up yet)
      - echo Installing MariaDB client...
      - sudo apt-get install -y mariadb-client

      # Install Git
      - echo Installing Git...
      - sudo apt-get install -y git

  pre_build:
    commands:
      # Clone the GitHub repository
      - echo Cloning repository...
      - git clone https://github.com/lurio84/CloudComputingProject.git
      - ls -a
      # Create .env file from example
      - cp .env.example .env

  build:
    commands:
      - cd Backend
      - ls -a
      - echo "Building Spring Boot application..."
      - chmod +x mvnw
      - ./mvnw clean package -DskipTests
      - cd ..

      # Docker イメージをビルド & プッシュ
      - echo "Building the Docker image..."
      - IMAGE_URI=211125652233.dkr.ecr.eu-north-1.amazonaws.com/collaborativenotesrepository:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 211125652233.dkr.ecr.eu-north-1.amazonaws.com
      - docker build -t collaborativenotesrepository .
      - docker tag collaborativenotesrepository:latest $IMAGE_URI
      - docker push $IMAGE_URI

      # image definitions を作成
      - echo "Writing image definitions..."
      - echo '[{"name":"collaborativenotesrepository","imageUri":"'$IMAGE_URI'"}]' > imagedefinitions.json  # ルートに作成
      - ls -l imagedefinitions.json
      - cat imagedefinitions.json

  post_build:
    commands:
      # Running the backend Spring Boot application
      - echo Running Spring Boot application...
      - java -jar target/*.jar &
      - ps aux | grep java
      - ls -lah target/ 
      - pwd

artifacts:
  files:
    - "**/target/*.jar"  # どこに `target/` があるかわからない場合の対応
    - imagedefinitions.json
  discard-paths: no




