version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing dependencies...
      - mvn install -DskipTests  # installフェーズで必要な依存関係をインストール

  build:
    commands:
      - echo Building the application...
      - mvn clean install -DskipTests
      - ls -alh target/  # targetディレクトリ内を確認
      - docker build -t $ImageName -f ./Dockerfile .  # ビルドコンテキストを確認

  post_build:
    commands:
      - echo Build completed.
      - docker build -t $ImageName -f ./Dockerfile .  # Dockerイメージをビルド
      - docker tag $ImageName:latest 21112
