version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing dependencies...
      - mvn install -DskipTests

  build:
    commands:
      - echo Building the application...
      - mvn clean install

  post_build:
    commands:
      - echo Build completed.
      - docker build -t $ImageName -f ./Dockerfile .
      - docker tag $ImageName:latest 211125652233.dkr.ecr.eu-north-1.amazonaws.com/$ImageName:latest
      - docker push 211125652233.dkr.ecr.eu-north-1.amazonaws.com/$ImageName:latest
