services:
  backend:
    build:
      context: . # ⬅️ Usamos la raíz del proyecto
      dockerfile: Backend/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./.env # ⬅️ También pasamos el archivo como variable de entorno

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
